package com.se.entity;

public class Administrator {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMINISTRATOR.ID
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMINISTRATOR.NAME
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMINISTRATOR.SCHOOL_NAME
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    private String schoolName;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMINISTRATOR
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    public Administrator(String id, String name, String schoolName) {
        this.id = id;
        this.name = name;
        this.schoolName = schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMINISTRATOR
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    public Administrator() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMINISTRATOR.ID
     *
     * @return the value of ADMINISTRATOR.ID
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMINISTRATOR.ID
     *
     * @param id the value for ADMINISTRATOR.ID
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMINISTRATOR.NAME
     *
     * @return the value of ADMINISTRATOR.NAME
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMINISTRATOR.NAME
     *
     * @param name the value for ADMINISTRATOR.NAME
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMINISTRATOR.SCHOOL_NAME
     *
     * @return the value of ADMINISTRATOR.SCHOOL_NAME
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMINISTRATOR.SCHOOL_NAME
     *
     * @param schoolName the value for ADMINISTRATOR.SCHOOL_NAME
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName == null ? null : schoolName.trim();
    }
}