package com.se.entity;

public class AssistantKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSISTANT.STUDENT_ID
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSISTANT.COURSE_ID
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ASSISTANT.SECTION_ID
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    private String sectionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSISTANT
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    public AssistantKey(String studentId, String courseId, String sectionId) {
        this.studentId = studentId;
        this.courseId = courseId;
        this.sectionId = sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSISTANT
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    public AssistantKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSISTANT.STUDENT_ID
     *
     * @return the value of ASSISTANT.STUDENT_ID
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSISTANT.STUDENT_ID
     *
     * @param studentId the value for ASSISTANT.STUDENT_ID
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSISTANT.COURSE_ID
     *
     * @return the value of ASSISTANT.COURSE_ID
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSISTANT.COURSE_ID
     *
     * @param courseId the value for ASSISTANT.COURSE_ID
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ASSISTANT.SECTION_ID
     *
     * @return the value of ASSISTANT.SECTION_ID
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    public String getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ASSISTANT.SECTION_ID
     *
     * @param sectionId the value for ASSISTANT.SECTION_ID
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    public void setSectionId(String sectionId) {
        this.sectionId = sectionId == null ? null : sectionId.trim();
    }
}