package com.se.entity;

public class Lab extends LabKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB.NAME
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB.REPORT_TEMPLATE
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    private String reportTemplate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    public Lab(String courseId, String labId, String name, String reportTemplate) {
        super(courseId, labId);
        this.name = name;
        this.reportTemplate = reportTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    public Lab() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB.NAME
     *
     * @return the value of LAB.NAME
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB.NAME
     *
     * @param name the value for LAB.NAME
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB.REPORT_TEMPLATE
     *
     * @return the value of LAB.REPORT_TEMPLATE
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    public String getReportTemplate() {
        return reportTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB.REPORT_TEMPLATE
     *
     * @param reportTemplate the value for LAB.REPORT_TEMPLATE
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    public void setReportTemplate(String reportTemplate) {
        this.reportTemplate = reportTemplate == null ? null : reportTemplate.trim();
    }
}