package com.se.entity;

public class LabKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB.COURSE_ID
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB.LAB_ID
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    private String labId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    public LabKey(String courseId, String labId) {
        this.courseId = courseId;
        this.labId = labId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    public LabKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB.COURSE_ID
     *
     * @return the value of LAB.COURSE_ID
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB.COURSE_ID
     *
     * @param courseId the value for LAB.COURSE_ID
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB.LAB_ID
     *
     * @return the value of LAB.LAB_ID
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    public String getLabId() {
        return labId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB.LAB_ID
     *
     * @param labId the value for LAB.LAB_ID
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    public void setLabId(String labId) {
        this.labId = labId == null ? null : labId.trim();
    }
}