package com.se.entity;

public class Section extends SectionKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SECTION.TERCHER_ID
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    private String tercherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SECTION.SEMETER
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    private Boolean semeter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SECTION.YEAR
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    private String year;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SECTION
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    public Section(String courseId, String sectionId, String tercherId, Boolean semeter, String year) {
        super(courseId, sectionId);
        this.tercherId = tercherId;
        this.semeter = semeter;
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SECTION
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    public Section() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SECTION.TERCHER_ID
     *
     * @return the value of SECTION.TERCHER_ID
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    public String getTercherId() {
        return tercherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SECTION.TERCHER_ID
     *
     * @param tercherId the value for SECTION.TERCHER_ID
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    public void setTercherId(String tercherId) {
        this.tercherId = tercherId == null ? null : tercherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SECTION.SEMETER
     *
     * @return the value of SECTION.SEMETER
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    public Boolean getSemeter() {
        return semeter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SECTION.SEMETER
     *
     * @param semeter the value for SECTION.SEMETER
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    public void setSemeter(Boolean semeter) {
        this.semeter = semeter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SECTION.YEAR
     *
     * @return the value of SECTION.YEAR
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SECTION.YEAR
     *
     * @param year the value for SECTION.YEAR
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }
}