package com.se.entity;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT.ID
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT.EMAIL
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT.NAME
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT.CLASSNUM
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    private String classnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT.SCHOOL_NAME
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    private String schoolName;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    public Student(String id, String email, String name, String classnum, String schoolName) {
        this.id = id;
        this.email = email;
        this.name = name;
        this.classnum = classnum;
        this.schoolName = schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    public Student() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.ID
     *
     * @return the value of STUDENT.ID
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.ID
     *
     * @param id the value for STUDENT.ID
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.EMAIL
     *
     * @return the value of STUDENT.EMAIL
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.EMAIL
     *
     * @param email the value for STUDENT.EMAIL
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.NAME
     *
     * @return the value of STUDENT.NAME
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.NAME
     *
     * @param name the value for STUDENT.NAME
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.CLASSNUM
     *
     * @return the value of STUDENT.CLASSNUM
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    public String getClassnum() {
        return classnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.CLASSNUM
     *
     * @param classnum the value for STUDENT.CLASSNUM
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    public void setClassnum(String classnum) {
        this.classnum = classnum == null ? null : classnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.SCHOOL_NAME
     *
     * @return the value of STUDENT.SCHOOL_NAME
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.SCHOOL_NAME
     *
     * @param schoolName the value for STUDENT.SCHOOL_NAME
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName == null ? null : schoolName.trim();
    }
}