package com.se.service;

import com.se.entity.Administrator;
import com.se.mapper.AdministratorMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class AdministratorImpl implements AdministratorService{
    @Autowired
    private AdministratorMapper administratorMapper;
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMINISTRATOR
     *
     * @mbg.generated Tue Oct 26 20:37:26 CST 2021
     */
    @Override
    public List<Administrator> selectAllAdministrator() {
        return administratorMapper.selectAllAdministrator();
    }
    @Override
    public int deleteByPrimaryKey(String id) {
        return administratorMapper.deleteByPrimaryKey(id);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMINISTRATOR
     *
     * @mbg.generated Tue Oct 26 20:37:26 CST 2021
     */
    @Override
    public int insert(com.se.entity.Administrator record) {
        return administratorMapper.insert(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMINISTRATOR
     *
     * @mbg.generated Tue Oct 26 20:37:26 CST 2021
     */
    @Override
    public int insertSelective(com.se.entity.Administrator record) {
        return administratorMapper.insertSelective(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMINISTRATOR
     *
     * @mbg.generated Tue Oct 26 20:37:26 CST 2021
     */
    @Override
    public com.se.entity.Administrator selectByPrimaryKey(String id) {
        return administratorMapper.selectByPrimaryKey(id);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMINISTRATOR
     *
     * @mbg.generated Tue Oct 26 20:37:26 CST 2021
     */
    @Override
    public int updateByPrimaryKeySelective(com.se.entity.Administrator record) {
        return administratorMapper.updateByPrimaryKeySelective(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMINISTRATOR
     *
     * @mbg.generated Tue Oct 26 20:37:26 CST 2021
     */
    @Override
    public int updateByPrimaryKey(com.se.entity.Administrator record) {
        return administratorMapper.updateByPrimaryKey(record);
    }
}
