package com.se.service;

import com.se.entity.AdministratorAccount;
import com.se.entity.AssistantKey;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class AssistantServiceImpl implements AssistantService{
    @Autowired
    private AssistantService assistantService;
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSISTANT
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    public int deleteByPrimaryKey(AssistantKey key) {
        return assistantService.deleteByPrimaryKey(key);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSISTANT
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    public int insert(AssistantKey record) {
        return assistantService.insert(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSISTANT
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    public int insertSelective(AssistantKey record) {
        return assistantService.insertSelective(record);
    }

}
