package com.se.service;

import com.se.entity.Files;
import com.se.mapper.FileMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class FileServiceImpl implements FileService{
    @Autowired
    private FileMapper fileMapper;
    @Override
    public int deleteByPrimaryKey(String url) {
        return fileMapper.deleteByPrimaryKey(url);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURSE
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    @Override
    public int insert(Files files) {
        return fileMapper.insert(files);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURSE
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
//    int insertSelective(Course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COURSE
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    @Override
    public List<Files> selectByCourseId(String courseId) {
        return fileMapper.selectByCourseId(courseId);
    }
    public List<Files> selectAllFile() {
        return fileMapper.selectAllFile();
    }
}
