package com.se.service;

import com.se.dto.LabInstenceDTO;
import com.se.entity.LabInstance;
import com.se.entity.LabInstanceKey;
import com.se.entity.SectionKey;

import java.util.List;

public interface LabInstanceService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB_INSTANCE
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    int deleteByPrimaryKey(LabInstanceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB_INSTANCE
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    int insert(LabInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB_INSTANCE
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    int insertSelective(LabInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB_INSTANCE
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    LabInstance selectByPrimaryKey(LabInstanceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB_INSTANCE
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    int updateByPrimaryKeySelective(LabInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB_INSTANCE
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    int updateByPrimaryKey(LabInstance record);

    LabInstenceDTO findOne(LabInstanceKey labInstanceKey);

    List<LabInstenceDTO> findLabInstanceOfSection(SectionKey sectionKey);

}
