package com.se.service;

import com.se.entity.Lab;
import com.se.entity.LabKey;

public interface LabService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    int deleteByPrimaryKey(LabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    int insert(Lab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    int insertSelective(Lab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    Lab selectByPrimaryKey(LabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    int updateByPrimaryKeySelective(Lab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    int updateByPrimaryKey(Lab record);
}
