package com.se.service;

import com.se.dto.FinishedReportDTO;
import com.se.dto.ReportDTO;
import com.se.entity.LabInstanceKey;
import com.se.entity.Report;
import com.se.entity.ReportKey;
import com.se.entity.SectionKey;

import java.util.List;

public interface ReportService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    int deleteByPrimaryKey(ReportKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    int insert(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    int insertSelective(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    Report selectByPrimaryKey(ReportKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    int updateByPrimaryKeySelective(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    int updateByPrimaryKey(Report record);
    List<Report> selectReport(String studentID);

    List<FinishedReportDTO> selectFinishedReports(String studentID);

    List<ReportDTO> findReportsOfLabInstance(LabInstanceKey labInstanceKey);

}
