package com.se.service;

import com.se.entity.School;

public interface SchoolService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHOOL
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHOOL
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    int insert(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCHOOL
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    int insertSelective(School record);
}
