package com.se.service;

import com.se.dto.SectionDTO;
import com.se.entity.Section;
import com.se.entity.SectionKey;
import com.se.mapper.SectionMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class SectionServiceImpl implements SectionService{
    @Autowired
    private SectionMapper sectionMapper;
    @Override
    public int deleteByPrimaryKey(SectionKey key) {
        return sectionMapper.deleteByPrimaryKey(key);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMINISTRATOR_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    @Override
    public int insert(Section record) {
        return sectionMapper.insert(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMINISTRATOR_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    @Override
    public int insertSelective(Section record) {
        return sectionMapper.insertSelective(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMINISTRATOR_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    @Override
    public Section selectByPrimaryKey(SectionKey key) {
        return sectionMapper.selectByPrimaryKey(key);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMINISTRATOR_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    @Override
    public int updateByPrimaryKeySelective(Section record) {
        return sectionMapper.updateByPrimaryKeySelective(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMINISTRATOR_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    @Override
    public int updateByPrimaryKey(Section record) {
        return sectionMapper.updateByPrimaryKey(record);
    }

    @Override
    public List<SectionDTO> findSectionsOfTeacher(String teacherId) {
        List<SectionDTO> secList = sectionMapper.findSectionsOfTeacher(teacherId);
        List<SectionKey> noGradingKey = sectionMapper.findSectionsOfTeacherHasNoGrading(teacherId);
        for (SectionDTO sectionDTO:secList){
            if (noGradingKey.contains(new SectionKey(sectionDTO.getCourseId(),sectionDTO.getSectionId()))) {
                sectionDTO.setHasNotGrading(true);
            }else{
                sectionDTO.setHasNotGrading(false);
            }
        }
        return secList;
    }

    @Override
    public SectionDTO findOneSection(String courseId, String section_Id) {
        return sectionMapper.findOneSection(courseId,section_Id);
    }
}
