package com.se.service;

import com.se.entity.Section;
import com.se.entity.SectionKey;

public interface SectionService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SECTION
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    int deleteByPrimaryKey(SectionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SECTION
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    int insert(Section record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SECTION
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    int insertSelective(Section record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SECTION
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    Section selectByPrimaryKey(SectionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SECTION
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    int updateByPrimaryKeySelective(Section record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SECTION
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    int updateByPrimaryKey(Section record);
}
