package com.se.service;

import com.se.dto.*;
import com.se.entity.Teacher;

import java.util.List;

public interface TeacherService {
    List<TeacherDTO> selectAllTeachers();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEACHER
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    List<CourseDTO> selectAllCourses(CourseINOTeacher courseINOTeacher);
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEACHER
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    int insert(TeacherINO teacherINO);

    int insertManyTeachers(List<TeacherINO> teacherINOs);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEACHER
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    int insertSelective(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEACHER
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    Teacher selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEACHER
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    int updateByPrimaryKeySelective(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEACHER
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    int updateByPrimaryKey(Teacher record);
}
