package com.se.service;

import com.se.entity.UnactivatedAccount;
import com.se.mapper.UnactivatedAccountMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class UnactivatedAccountServiceImpl implements UnactivatedAccountService{
    @Autowired
    private UnactivatedAccountMapper unactivatedAccountMapper;
    @Override
    public int deleteByPrimaryKey(String email) {
        return unactivatedAccountMapper.deleteByPrimaryKey(email);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMINISTRATOR_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    @Override
    public int insert(UnactivatedAccount record) {
        return unactivatedAccountMapper.insert(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMINISTRATOR_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    @Override
    public int insertSelective(UnactivatedAccount record) {
        return unactivatedAccountMapper.insertSelective(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMINISTRATOR_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    @Override
    public UnactivatedAccount selectByPrimaryKey(String email) {
        return unactivatedAccountMapper.selectByPrimaryKey(email);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMINISTRATOR_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    @Override
    public int updateByPrimaryKeySelective(UnactivatedAccount record) {
        return unactivatedAccountMapper.updateByPrimaryKeySelective(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMINISTRATOR_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    @Override
    public int updateByPrimaryKey(UnactivatedAccount record) {
        return unactivatedAccountMapper.updateByPrimaryKey(record);
    }
}
