package com.se.service;

import com.se.entity.AdministratorAccount;
import com.se.entity.UnactivatedAccount;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class UnactivatedAccountServiceImpl implements UnactivatedAccountService{
    @Autowired
    private UnactivatedAccountService unactivatedAccountService;
    public int deleteByPrimaryKey(String email) {
        return unactivatedAccountService.deleteByPrimaryKey(email);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMINISTRATOR_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    public int insert(UnactivatedAccount record) {
        return unactivatedAccountService.insert(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMINISTRATOR_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    public int insertSelective(UnactivatedAccount record) {
        return unactivatedAccountService.insertSelective(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMINISTRATOR_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    public UnactivatedAccount selectByPrimaryKey(String email) {
        return unactivatedAccountService.selectByPrimaryKey(email);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMINISTRATOR_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    public int updateByPrimaryKeySelective(UnactivatedAccount record) {
        return unactivatedAccountService.updateByPrimaryKeySelective(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMINISTRATOR_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    public int updateByPrimaryKey(UnactivatedAccount record) {
        return unactivatedAccountService.updateByPrimaryKey(record);
    }
}
