package com.se.mapper;

import com.se.entity.Administrator;

public interface AdministratorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMINISTRATOR
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMINISTRATOR
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    int insert(Administrator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMINISTRATOR
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    int insertSelective(Administrator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMINISTRATOR
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    Administrator selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMINISTRATOR
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    int updateByPrimaryKeySelective(Administrator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADMINISTRATOR
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    int updateByPrimaryKey(Administrator record);
}