package com.se.mapper;

import com.se.entity.AssistantKey;

public interface AssistantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSISTANT
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    int deleteByPrimaryKey(AssistantKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSISTANT
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    int insert(AssistantKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSISTANT
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    int insertSelective(AssistantKey record);
}