package com.se.mapper;

import com.se.dto.LabInstenceDTO;
import com.se.entity.LabInstance;
import com.se.entity.LabInstanceKey;
import com.se.entity.SectionKey;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface LabInstanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB_INSTANCE
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    int deleteByPrimaryKey(LabInstanceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB_INSTANCE
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    int insert(LabInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB_INSTANCE
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    int insertSelective(LabInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB_INSTANCE
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    LabInstance selectByPrimaryKey(LabInstanceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB_INSTANCE
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    int updateByPrimaryKeySelective(LabInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB_INSTANCE
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    int updateByPrimaryKey(LabInstance record);

    @Select("SELECT * FROM LAB_INSTANCE NATURAL JOIN LAB WHERE COURSE_ID = #{courseId} and SECTION_ID = #{sectionId} AND LAB_ID = #{labId}")
    LabInstenceDTO findOne(LabInstanceKey labInstanceKey);

    @Select("SELECT * FROM LAB_INSTANCE NATURAL JOIN LAB WHERE COURSE_ID = #{courseId} and SECTION_ID = #{sectionId}")
    List<LabInstenceDTO> findLabInstanceOfSection(SectionKey sectionKey);
}