package com.se.mapper;

import com.se.entity.Lab;
import com.se.entity.LabKey;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface LabMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    int deleteByPrimaryKey(LabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    int insert(Lab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    int insertSelective(Lab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    Lab selectByPrimaryKey(LabKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    int updateByPrimaryKeySelective(Lab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    int updateByPrimaryKey(Lab record);
}