package com.se.mapper;

import com.se.dto.FinishedReportDTO;
import com.se.dto.ReportDTO;
import com.se.entity.LabInstanceKey;
import com.se.entity.Report;
import com.se.entity.ReportKey;
import com.se.entity.SectionKey;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface ReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    int deleteByPrimaryKey(ReportKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    int insert(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    int insertSelective(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    Report selectByPrimaryKey(ReportKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    int updateByPrimaryKeySelective(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPORT
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    int updateByPrimaryKey(Report record);
    List<Report> selectReport(String studentID);

    List<FinishedReportDTO> selectFinishedReports(String studentID);

    @Select("SELECT * FROM REPORT JOIN STUDENT ON STUDENT_ID = ID WHERE COURSE_ID = #{courseId} and SECTION_ID = #{sectionId} and LAB_ID = #{labId}")
    List<ReportDTO> findReportsOfLabInstance(LabInstanceKey labInstanceKey);
}