package com.se.mapper;

import com.se.entity.StudentAccount;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface StudentAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    int insert(StudentAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    int insertSelective(StudentAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    StudentAccount selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    int updateByPrimaryKeySelective(StudentAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 09:24:02 CST 2021
     */
    int updateByPrimaryKey(StudentAccount record);
}