package com.se.mapper;

import com.se.entity.StudentAccount;

public interface StudentAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    int insert(StudentAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    int insertSelective(StudentAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    StudentAccount selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    int updateByPrimaryKeySelective(StudentAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 21:50:19 CST 2021
     */
    int updateByPrimaryKey(StudentAccount record);
}