package com.se.mapper;

import com.se.entity.Takes;
import com.se.entity.TakesKey;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface TakesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAKES
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    int deleteByPrimaryKey(TakesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAKES
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    int insert(Takes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAKES
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    int insertSelective(Takes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAKES
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    Takes selectByPrimaryKey(TakesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAKES
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    int updateByPrimaryKeySelective(Takes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAKES
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    int updateByPrimaryKey(Takes record);
}