package com.se.mapper;

import com.se.entity.UnactivatedAccount;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface UnactivatedAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNACTIVATED_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    int deleteByPrimaryKey(String email);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNACTIVATED_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    int insert(UnactivatedAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNACTIVATED_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    int insertSelective(UnactivatedAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNACTIVATED_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    UnactivatedAccount selectByPrimaryKey(String email);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNACTIVATED_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    int updateByPrimaryKeySelective(UnactivatedAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNACTIVATED_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    int updateByPrimaryKey(UnactivatedAccount record);
}