package com.se.mapper;

import com.se.dto.TeacherDTO;
import com.se.dto.UnactivatedAccountDTO;
import com.se.entity.UnactivatedAccount;
import com.sun.org.apache.xpath.internal.operations.Bool;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface UnactivatedAccountMapper {
    int activateAccount(String Id);

    List<UnactivatedAccountDTO> selectAllUnactivatedAccounts();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNACTIVATED_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNACTIVATED_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    int insert(UnactivatedAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNACTIVATED_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    int insertSelective(UnactivatedAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNACTIVATED_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    UnactivatedAccount selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNACTIVATED_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    int updateByPrimaryKeySelective(UnactivatedAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNACTIVATED_ACCOUNT
     *
     * @mbg.generated Wed Oct 27 22:15:26 CST 2021
     */
    int updateByPrimaryKey(UnactivatedAccount record);
}